from typing import Dict

from .optflags import OptFlags, TriState, MetaFlags
from .sticky_buffer import StickyBuffer

__all__ = (
    'sigmatch_table',
    'alias_table',
)

sigmatch_table = {
    'alert': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'app-layer-event': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'app-layer-protocol': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'asn1': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'base64_data': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'base64_decode': OptFlags(
        quotes=TriState.NONE,
        values=TriState.OPTIONAL,
        negation=False,
    ),
    'bsize': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'bypass': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'byte_extract': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'byte_jump': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'byte_math': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'byte_test': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'cip_service': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'classtype': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=False, multiple=False),
    ),
    'compress_whitespace': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'config': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'content': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'datarep': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dataset': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dcerpc.iface': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dcerpc.opnum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dcerpc.stub_data': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.DCERPC_STUB_DATA,
    ),
    'decode-event': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'depth': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        is_content_modifier=True,
    ),
    'detection_filter': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dhcp.leasetime': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dhcp.rebinding_time': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dhcp.renewal_time': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'distance': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        is_content_modifier=True,
    ),
    'dnp3.data': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.DNP3_DATA,
    ),
    'dnp3_func': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dnp3_ind': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dnp3_obj': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dns.opcode': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'dns.query': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.DNS_QUERY,
    ),
    'dotprefix': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'dsize': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'endswith': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_modifier=True,
    ),
    'engine-event': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'enip_command': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'fast_pattern': OptFlags(
        quotes=TriState.NONE,
        values=TriState.OPTIONAL,
        negation=False,
        is_content_modifier=True,
    ),
    'file.data': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'file.magic': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.FILE_MAGIC,
    ),
    'file.name': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.FILE_NAME,
    ),
    'fileext': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'filemagic': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'filemd5': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'filename': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'filesha1': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'filesha256': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'filesize': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'filestore': OptFlags(
        quotes=TriState.NONE,
        values=TriState.OPTIONAL,
        negation=False,
    ),
    'flow': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'flow.age': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'flowbits': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'flowint': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'flowvar': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'fragbits': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'fragoffset': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'frame': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        sticky_buffer=StickyBuffer.FRAME,
    ),
    'ftpbounce': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'ftpdata_command': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'geoip': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'gid': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'header_lowercase': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'hostbits': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http.accept': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_ACCEPT,
    ),
    'http.accept_enc': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_ACCEPT_ENC,
    ),
    'http.accept_lang': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_ACCEPT_LANG,
    ),
    'http.connection': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_CONNECTION,
    ),
    'http.content_len': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_CONTENT_LEN,
    ),
    'http.content_type': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_CONTENT_TYPE,
    ),
    'http.cookie': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_COOKIE,
    ),
    'http.header': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_HEADER,
    ),
    'http.header.raw': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_HEADER_RAW,
    ),
    'http.header_names': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_HEADER_NAMES,
    ),
    'http.host': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_HOST,
    ),
    'http.host.raw': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_HOST_RAW,
    ),
    'http.location': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_LOCATION,
    ),
    'http.method': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_METHOD,
    ),
    'http.protocol': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_PROTOCOL,
    ),
    'http.referer': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_REFERER,
    ),
    'http.request_body': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_REQUEST_BODY,
    ),
    'http.request_header': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_REQUEST_HEADER,
    ),
    'http.request_line': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_REQUEST_LINE,
    ),
    'http.response_body': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_RESPONSE_BODY,
    ),
    'http.response_header': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_RESPONSE_HEADER,
    ),
    'http.response_line': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_RESPONSE_LINE,
    ),
    'http.server': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_SERVER,
    ),
    'http.start': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_START,
    ),
    'http.stat_code': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_STAT_CODE,
    ),
    'http.stat_msg': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_STAT_MSG,
    ),
    'http.uri': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_URI,
    ),
    'http.uri.raw': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_URI_RAW,
    ),
    'http.user_agent': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP_USER_AGENT,
    ),
    'http2.errorcode': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http2.frametype': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http2.header_name': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.HTTP2_HEADER_NAME,
    ),
    'http2.priority': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http2.settings': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http2.size_update': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http2.window': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'http_client_body': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_cookie': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_header': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_host': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_method': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_raw_header': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_raw_host': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_raw_uri': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_server_body': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_stat_code': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_stat_msg': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_uri': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'http_user_agent': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'icmp_id': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'icmp_seq': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'icmpv4-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'icmpv4.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.ICMPV4_HDR,
    ),
    'icmpv6-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'icmpv6.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.ICMPV6_HDR,
    ),
    'icmpv6.mtu': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'icode': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'id': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ike.chosen_sa_attribute': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ike.exchtype': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ike.init_spi': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IKE_INIT_SPI,
    ),
    'ike.key_exchange_payload': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IKE_KEY_EXCHANGE_PAYLOAD,
    ),
    'ike.key_exchange_payload_length': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ike.nonce_payload': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IKE_NONCE_PAYLOAD,
    ),
    'ike.nonce_payload_length': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ike.resp_spi': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IKE_RESP_SPI,
    ),
    'ike.vendor': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IKE_VENDOR,
    ),
    'ip.dst': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IP_DST,
    ),
    'ip.src': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IP_SRC,
    ),
    'ip_proto': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ipopts': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'iprep': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ipv4-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ipv4.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IPV4_HDR,
    ),
    'ipv6.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.IPV6_HDR,
    ),
    'isdataat': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'itype': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ja3.hash': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.JA3_HASH,
    ),
    'ja3.string': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.JA3_STRING,
    ),
    'ja3s.hash': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.JA3S_HASH,
    ),
    'ja3s.string': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.JA3S_STRING,
    ),
    'ja4.hash': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.JA4_HASH,
    ),
    'krb5.cname': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.KRB5_CNAME,
    ),
    'krb5.sname': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.KRB5_SNAME,
    ),
    'krb5.ticket_encryption': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'krb5_err_code': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'krb5_msg_type': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'l3_proto': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'lua': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'metadata': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=False, multiple=True),
    ),
    'modbus': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.connack.session_present': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.connect.clientid': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.connect.flags': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.connect.password': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.connect.username': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.connect.willmessage': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.connect.willtopic': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.flags': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.protocol_version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.publish.message': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.publish.topic': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'mqtt.qos': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.reason_code': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.subscribe.topic': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.MQTT_SUBSCRIBE_TOPIC,
    ),
    'mqtt.type': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'mqtt.unsubscribe.topic': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.MQTT_UNSUBSCRIBE_TOPIC,
    ),
    'msg': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=True, multiple=False),
    ),
    'nfq_set_mark': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'nfs.version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'nfs_procedure': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'noalert': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'nocase': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_modifier=True,
    ),
    'offset': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        is_content_modifier=True,
    ),
    'pcre': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'pcrexform': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=False,
        is_content_transform=True,
    ),
    'pkt_data': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'pktvar': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'prefilter': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'priority': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'quic.cyu.hash': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'quic.cyu.string': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'quic.sni': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.QUIC_SNI,
    ),
    'quic.ua': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.QUIC_UA,
    ),
    'quic.version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.QUIC_VERSION,
    ),
    'rawbytes': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'reference': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=False, multiple=True),
    ),
    'replace': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'requires': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'rev': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=False, multiple=False),
    ),
    'rfb.name': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.RFB_NAME,
    ),
    'rfb.secresult': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'rfb.sectype': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'rpc': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'sameip': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sid': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=True, multiple=False),
    ),
    'sip.method': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.protocol': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.request_line': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.response_line': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.stat_code': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.stat_msg': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'sip.uri': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'smb.named_pipe': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SMB_NAMED_PIPE,
    ),
    'smb.ntlmssp_domain': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SMB_NTLMSSP_DOMAIN,
    ),
    'smb.ntlmssp_user': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SMB_NTLMSSP_USER,
    ),
    'smb.share': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SMB_SHARE,
    ),
    'snmp.community': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SNMP_COMMUNITY,
    ),
    'snmp.pdu_type': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'snmp.usm': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SNMP_USM,
    ),
    'snmp.version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ssh.hassh': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_HASSH,
    ),
    'ssh.hassh.server': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_HASSH_SERVER,
    ),
    'ssh.hassh.server.string': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_HASSH_SERVER_STRING,
    ),
    'ssh.hassh.string': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_HASSH_STRING,
    ),
    'ssh.proto': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_PROTO,
    ),
    'ssh.protoversion': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ssh.software': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.SSH_SOFTWARE,
    ),
    'ssh.softwareversion': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ssl_state': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'ssl_version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'startswith': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_modifier=True,
    ),
    'stream-event': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'stream_size': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'strip_pseudo_headers': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'strip_whitespace': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'tag': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'target': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        meta=MetaFlags(required=False, multiple=True),
    ),
    'tcp.ack': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcp.flags': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcp.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TCP_HDR,
    ),
    'tcp.mss': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcp.seq': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcp.window': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcpv4-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tcpv6-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'template': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'template2': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'threshold': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tls.cert_chain_len': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tls.cert_fingerprint': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_CERT_FINGERPRINT,
    ),
    'tls.cert_issuer': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_CERT_ISSUER,
    ),
    'tls.cert_serial': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_CERT_SERIAL,
    ),
    'tls.cert_subject': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_CERT_SUBJECT,
    ),
    'tls.certs': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_CERTS,
    ),
    'tls.fingerprint': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'tls.issuerdn': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'tls.random': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_RANDOM,
    ),
    'tls.random_bytes': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_RANDOM_BYTES,
    ),
    'tls.random_time': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_RANDOM_TIME,
    ),
    'tls.sni': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.TLS_SNI,
    ),
    'tls.subject': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'tls.version': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tls_cert_expired': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'tls_cert_notafter': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tls_cert_notbefore': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'tls_cert_valid': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'tls_store': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
    ),
    'to_lowercase': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'to_md5': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'to_sha1': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'to_sha256': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'to_uppercase': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'tos': OptFlags(
        quotes=TriState.OPTIONAL,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'ttl': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'udp.hdr': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        sticky_buffer=StickyBuffer.UDP_HDR,
    ),
    'udpv4-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'udpv6-csum': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'uricontent': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=True,
    ),
    'urilen': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'url_decode': OptFlags(
        quotes=TriState.NONE,
        values=TriState.NONE,
        negation=False,
        is_content_transform=True,
    ),
    'within': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
        is_content_modifier=True,
    ),
    'xbits': OptFlags(
        quotes=TriState.NONE,
        values=TriState.MANDATORY,
        negation=False,
    ),
    'xor': OptFlags(
        quotes=TriState.MANDATORY,
        values=TriState.MANDATORY,
        negation=False,
        is_content_transform=True,
    ),
}


alias_table: Dict[str, str] = {
    'dce_iface': 'dcerpc.iface',
    'dce_opnum': 'dcerpc.opnum',
    'dce_stub_data': 'dcerpc.stub_data',
    'dnp3_data': 'dnp3.data',
    'dnp3.func': 'dnp3_func',
    'dnp3.ind': 'dnp3_ind',
    'dnp3.obj': 'dnp3_obj',
    'dns_query': 'dns.query',
    'file_data': 'file.data',
    'http_accept': 'http.accept',
    'http_accept_enc': 'http.accept_enc',
    'http_accept_lang': 'http.accept_lang',
    'http_connection': 'http.connection',
    'http_content_len': 'http.content_len',
    'http_content_type': 'http.content_type',
    'http_header_names': 'http.header_names',
    'http_protocol': 'http.protocol',
    'http_referer': 'http.referer',
    'http_request_line': 'http.request_line',
    'http_response_line': 'http.response_line',
    'http_start': 'http.start',
    'http.uri.normalized': 'http.uri',
    'ja3_hash': 'ja3.hash',
    'ja3_string': 'ja3.string',
    'ja4_hash': 'ja4.hash',
    'krb5_cname': 'krb5.cname',
    'krb5_sname': 'krb5.sname',
    'luajit': 'lua',
    'mqtt.connack.return_code': 'mqtt.reason_code',
    'nfs_version': 'nfs.version',
    'smb_named_pipe': 'smb.named_pipe',
    'smb_share': 'smb.share',
    'ssh-hassh': 'ssh.hassh',
    'ssh-hassh-server': 'ssh.hassh.server',
    'ssh-hassh-server-string': 'ssh.hassh.server.string',
    'ssh-hassh-string': 'ssh.hassh.string',
    'ssh_proto': 'ssh.proto',
    'ssh_software': 'ssh.software',
    'ack': 'tcp.ack',
    'flags': 'tcp.flags',
    'seq': 'tcp.seq',
    'window': 'tcp.window',
    'tls_cert_fingerprint': 'tls.cert_fingerprint',
    'tls_cert_issuer': 'tls.cert_issuer',
    'tls_cert_serial': 'tls.cert_serial',
    'tls_cert_subject': 'tls.cert_subject',
    'tls_sni': 'tls.sni',
    'tls.store': 'tls_store',
}
