from enum import Enum

__all__ = (
    'StickyBuffer',
)


class StickyBuffer(Enum):
    PKT_DATA = 'pkt_data'

    DCERPC_STUB_DATA = 'dcerpc.stub_data'
    DNP3_DATA = 'dnp3.data'
    DNS_QUERY = 'dns.query'
    FILE_DATA = 'file.data'
    FILE_MAGIC = 'file.magic'
    FILE_NAME = 'file.name'
    FRAME = 'frame'
    HTTP_ACCEPT = 'http.accept'
    HTTP_ACCEPT_ENC = 'http.accept_enc'
    HTTP_ACCEPT_LANG = 'http.accept_lang'
    HTTP_CONNECTION = 'http.connection'
    HTTP_CONTENT_LEN = 'http.content_len'
    HTTP_CONTENT_TYPE = 'http.content_type'
    HTTP_COOKIE = 'http.cookie'
    HTTP_HEADER = 'http.header'
    HTTP_HEADER_RAW = 'http.header.raw'
    HTTP_HEADER_NAMES = 'http.header_names'
    HTTP_HOST = 'http.host'
    HTTP_HOST_RAW = 'http.host.raw'
    HTTP_LOCATION = 'http.location'
    HTTP_METHOD = 'http.method'
    HTTP_PROTOCOL = 'http.protocol'
    HTTP_REFERER = 'http.referer'
    HTTP_REQUEST_BODY = 'http.request_body'
    HTTP_REQUEST_HEADER = 'http.request_header'
    HTTP_REQUEST_LINE = 'http.request_line'
    HTTP_RESPONSE_BODY = 'http.response_body'
    HTTP_RESPONSE_HEADER = 'http.response_header'
    HTTP_RESPONSE_LINE = 'http.response_line'
    HTTP_SERVER = 'http.server'
    HTTP_START = 'http.start'
    HTTP_STAT_CODE = 'http.stat_code'
    HTTP_STAT_MSG = 'http.stat_msg'
    HTTP_URI = 'http.uri'
    HTTP_URI_RAW = 'http.uri.raw'
    HTTP_USER_AGENT = 'http.user_agent'
    HTTP2_HEADER_NAME = 'http2.header_name'
    ICMPV4_HDR = 'icmpv4.hdr'
    ICMPV6_HDR = 'icmpv6.hdr'
    IKE_INIT_SPI = 'ike.init_spi'
    IKE_KEY_EXCHANGE_PAYLOAD = 'ike.key_exchange_payload'
    IKE_NONCE_PAYLOAD = 'ike.nonce_payload'
    IKE_RESP_SPI = 'ike.resp_spi'
    IKE_VENDOR = 'ike.vendor'
    IP_DST = 'ip.dst'
    IP_SRC = 'ip.src'
    IPV4_HDR = 'ipv4.hdr'
    IPV6_HDR = 'ipv6.hdr'
    JA3_HASH = 'ja3.hash'
    JA3_STRING = 'ja3.string'
    JA3S_HASH = 'ja3s.hash'
    JA3S_STRING = 'ja3s.string'
    JA4_HASH = 'ja4.hash'
    KRB5_CNAME = 'krb5.cname'
    KRB5_SNAME = 'krb5.sname'
    MQTT_SUBSCRIBE_TOPIC = 'mqtt.subscribe.topic'
    MQTT_UNSUBSCRIBE_TOPIC = 'mqtt.unsubscribe.topic'
    QUIC_SNI = 'quic.sni'
    QUIC_UA = 'quic.ua'
    QUIC_VERSION = 'quic.version'
    RFB_NAME = 'rfb.name'
    SMB_NAMED_PIPE = 'smb.named_pipe'
    SMB_NTLMSSP_DOMAIN = 'smb.ntlmssp_domain'
    SMB_NTLMSSP_USER = 'smb.ntlmssp_user'
    SMB_SHARE = 'smb.share'
    SNMP_COMMUNITY = 'snmp.community'
    SNMP_USM = 'snmp.usm'
    SSH_HASSH = 'ssh.hassh'
    SSH_HASSH_SERVER = 'ssh.hassh.server'
    SSH_HASSH_SERVER_STRING = 'ssh.hassh.server.string'
    SSH_HASSH_STRING = 'ssh.hassh.string'
    SSH_PROTO = 'ssh.proto'
    SSH_SOFTWARE = 'ssh.software'
    TCP_HDR = 'tcp.hdr'
    TLS_CERT_FINGERPRINT = 'tls.cert_fingerprint'
    TLS_CERT_ISSUER = 'tls.cert_issuer'
    TLS_CERT_SERIAL = 'tls.cert_serial'
    TLS_CERT_SUBJECT = 'tls.cert_subject'
    TLS_CERTS = 'tls.certs'
    TLS_RANDOM = 'tls.random'
    TLS_RANDOM_BYTES = 'tls.random_bytes'
    TLS_RANDOM_TIME = 'tls.random_time'
    TLS_SNI = 'tls.sni'
    UDP_HDR = 'udp.hdr'

    @property
    def buf_name(self) -> str:
        return self.name.lower()

    @property
    def arg_name(self) -> str:
        return self.name.lower().replace('_', '-')
